#!/usr/bin/env node

require('source-map-support').install();
const path = require('path');
const importer = require('./dist/index');

const dir = path.resolve(__dirname, process.argv[2] || '../src/js/data');
(async () => { 
    await Promise.all([importer.importSets(dir), importer.importRandom(dir)]);
})().catch(err => console.error(err));
